version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - MONGODB_URI= # put your MONGODB URI here
    # if you are using mongodb container, uncomment below
    # depends_on:
    #   - mongo

#Uncomment Below if you want to use mongodb container
  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - mongo-data:/data/db

# volumes:
#   mongo-data:
